services:
  mysql:
    container_name: 'guide-mysql'
    image: 'mysql:8.0'
    environment:
      MYSQL_DATABASE: test_database
      # MYSQL_USER: ${MYSQL_USER}
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
